
[env:my_esp32_sz-openCB-v6]
board = esp32dev
build_flags = ${env.build_flags}
    -DHOYMILES_PIN_MISO=GPIO_NUM_19
    -DHOYMILES_PIN_MOSI=GPIO_NUM_23
    -DHOYMILES_PIN_SCLK=GPIO_NUM_18
    -DHOYMILES_PIN_IRQ=GPIO_NUM_16
    -DHOYMILES_PIN_CE=GPIO_NUM_4
    -DHOYMILES_PIN_CS=GPIO_NUM_5
    -DLED0=GPIO_NUM_33
    -DLED1=GPIO_NUM_25
    -DCMT_CLK=GPIO_NUM_12
    -DCMT_CS=GPIO_NUM_27
    -DCMT_FCS=GPIO_NUM_26
    -DCMT_SDIO=GPIO_NUM_14
    -DCMT_GPIO2=GPIO_NUM_NC
    -DCMT_GPIO3=GPIO_NUM_NC
monitor_port = COM3
upload_port = COM3


[env:my_esp32_rs-platinen]
board = esp32dev
build_flags = ${env.build_flags}
    -DHOYMILES_PIN_MISO=GPIO_NUM_19
    -DHOYMILES_PIN_MOSI=GPIO_NUM_23
    -DHOYMILES_PIN_SCLK=GPIO_NUM_18
    -DHOYMILES_PIN_IRQ=GPIO_NUM_16
    -DHOYMILES_PIN_CE=GPIO_NUM_4
    -DHOYMILES_PIN_CS=GPIO_NUM_5
    -DLED0=GPIO_NUM_32
    -DLED1=GPIO_NUM_25
    -DCMT_CLK=GPIO_NUM_12
    -DCMT_CS=GPIO_NUM_27
    -DCMT_FCS=GPIO_NUM_26
    -DCMT_SDIO=GPIO_NUM_14
    -DCMT_GPIO2=GPIO_NUM_NC
    -DCMT_GPIO3=GPIO_NUM_34
monitor_port = COM3
upload_port = COM3


[env:my_wt32_eth01]
; http://www.wireless-tag.com/portfolio/wt32-eth01/
board = wt32-eth01
board_build.partitions = partitions_custom_8mb.csv
build_flags = ${env.build_flags}
    -DHOYMILES_PIN_MISO=GPIO_NUM_NC
    -DHOYMILES_PIN_MOSI=GPIO_NUM_NC
    -DHOYMILES_PIN_SCLK=GPIO_NUM_NC
    -DHOYMILES_PIN_IRQ=GPIO_NUM_NC
    -DHOYMILES_PIN_CE=GPIO_NUM_NC
    -DHOYMILES_PIN_CS=GPIO_NUM_NC
    -DOPENDTU_ETHERNET
    -DLED0=GPIO_NUM_NC
    -DLED1=GPIO_NUM_NC
    -DCMT_CLK=GPIO_NUM_15
    -DCMT_CS=GPIO_NUM_12
    -DCMT_FCS=GPIO_NUM_4
    -DCMT_SDIO=GPIO_NUM_14
    -DDISPLAY_TYPE=3
    -DDISPLAY_DATA=GPIO_NUM_32
    -DDISPLAY_CLK=GPIO_NUM_33
monitor_port = COM8
upload_port = COM8
